### ISSUE TITLE
Some description of the last commits…

### ISSUE THREAD

**Issue by alappe** [gianlucadelgobbo/avnode#22]
Hey @donostiastudio,

I am wondering about the purpose of 43bc37479 and the following two commits… Could you give me a short description? To me, it looks like a merge gone bad where the plugin registration is moved from `app/server/` back to `app.js`…

Best regards
Andreas

**Comment by donostiastudio** [comment]
Hi @alappe 
don't care about [43bc374](https://github.com/gianlucadelgobbo/avnode/commit/43bc3747958f18a223d4a423bc808e09342f9c42): it was just a commit test. You can delete and overwrite it as you want.

We're now working on some jade files like [this](https://github.com/gianlucadelgobbo/avnode/blob/master/app/server/views/performer_inc_author_header.jade) in order to develop interface and layouts on public side. We will commit it soon. 

Best regards
Donostia

**Comment by alappe** [comment]
Ok, thanks
